### ISSUE TITLE
Object page ID to accession number map

### ISSUE THREAD

**Issue by thisisaaronland** [vanda/etc-docs#20]
Is it possible to get a mapping on all the accession numbers for their corresponding web pages?

For example `E.110-2012` maps to https://collections.vam.ac.uk/item/O1243176

There doesn't seem to be a public open data set that I can use to derive this information and glancing at the open issues it appears search is bounded by the "maximum 10K results" limit set by Elasticsearch (or equivalent).

The goal is to be able to add the V&A to the "Fake Accession Number APIs" project:

https://github.com/aaronland/fake-accession-number-apis

Ideally the goal is _not_ add the V&A to the "Fake Accession Number APIs" project but until it's possible to link directly to an object page using an accession number it will have to do :-)

**Comment by atiro** [comment]
Very belated reply @thisisaaronland - would have to be an export of the two fields for all objects, there isn't any meaningful mapping. But this API param should work:

  http://api.vam.ac.uk/v2/objects/search?kw_accession_number=E.110-2012

Although part numbers will confuse it.
