### ISSUE TITLE
How to include "- record - creditLine",  "record - objectHistory" & "record - briefDescription" in "https://api.vam.ac.uk/v2/objects/search?" results? 

### ISSUE THREAD

**Issue by sinjabiaa** [vanda/etc-docs#22]
Hello V&A, 

For a uni project about the V&A's accessions of photographs from North Africa and Middle East, 
it would be helpful if the spreadsheet columns:  "- record - creditLine",  "record - objectHistory", "record - historicalContext" & "record - briefDescription" would be integrated in the spreadsheet result of the query
https://api.vam.ac.uk/v2/objects/search?id_technique=AAT54225&id_place=x29512&year_made_from=1840&year_made_to=1950&page_size=100

I could only figure out to query these columns for each object/photograph individually.
For instance: https://api.vam.ac.uk/v2/museumobject/O1283179

How can I query/include these columns in question in the framework of my broader research? Is it possible?  
So I don't need to query each object individually to analyse the information of the columns in question.

I would be glad to receive a short feedback. Thanks.

**Comment by atiro** [comment]
Sorry @sinjabiaa I've just seen this. I think the problem with that is those fields can be very long free text fields, which doesn't really suit the CSV format, I would say the JSON object response is the best way to handle currently, although I understand the issue you raise in having to request each. Ultimately, something like a SPARQL API would allow for selection of relevant fields for a query, I'm hopeful we can return to implement something like this at some point.
