### ISSUE TITLE
Unable to get all records with query

### ISSUE THREAD

**Issue by shiveshsood** [vanda/etc-docs#42]
Hi, 
I'm trying to query the API for images of textiles from South Asia. The query I am using is as below - 
https://api.vam.ac.uk/v2/objects/search?images_exist=true&id_category=THES48885&id_place=x29790&kw_object_type=Textile

While the `record_count` thrown back is 205, the `records` dict only has 15 items. Please let me know if I am missing something or need an API key to get all record details.

Thanks!

**Comment by atiro** [comment]
Hi @shiveshsood , the results are paged so you will need to iterate through the results, see https://developers.vam.ac.uk/guide/v2/results/introduction.html#page-of-results-page

**Comment by atiro** [comment]
Assume this is resolved, please re-open if not
